FROM python:3.12-slim

# Evitar .pyc y mejorar logs
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Copiar pyproject y dependencias Python
COPY pyproject.toml ./

RUN pip install --upgrade pip setuptools wheel && \
    pip install waitress && \
    pip install -e .

# Copiar el código fuente
COPY . .

# Exponer puerto de la app
EXPOSE 8000

# Ejecutar con Waitress
CMD ["waitress-serve", "--listen=0.0.0.0:8000", "main:app"]